version: '3.9'
services:
  mysql-kc:
    image: mysql:8.0.27
    ports:
      - 3366:3306
    restart: unless-stopped
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: keycloak_db
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - keycloak-and-mysql-volume:/var/lib/mysql
    networks:
      - keycloak-and-mysql-network

  keycloak-w:
    image: quay.io/keycloak/keycloak:22.0.4
    command: start-dev
    ports:
      - 9081:8080
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN : admin
      KEYCLOAK_ADMIN_PASSWORD: admin@1234
      KC_DB: mysql
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: password
      KC_DB_URL: jdbc:mysql://mysql-kc:3306/keycloak_db
      PROXY_ADDRESS_FORWARDING: 'true'
      KC_PROXY: edge
      KC_HOSTNAME: keycloak.domain.com
      KC_HOSTNAME_STRICT_HTTPS: 'true'
    depends_on:
      - mysql-kc
    networks:
      - keycloak-and-mysql-network

networks:
  keycloak-and-mysql-network:

volumes:
  keycloak-and-mysql-volume:
