

server:
  port: 9095
  servlet:
    context-path: /api/integration
api:
  stripe:
    key: stripe_key

aws:
  s3:
    url: https://eu2.contabostorage.com
  access:
    keyId: accessKey_update
  secret:
    access:
      key: secretAccessKey_update
chat-gpt:
  key: sk-Chat-GPT-KEY


jasypt:
  encryptor:
    privateKeyFormat: PEM
    privateKeyLocation: classpath:private_key.pem

test:
  password:
    encryption: ENC(FOS1T53oMZrkmegz3k3AMQN09D2Se/BHzr9WXjz+HTzfKK6PorSgly40F/B2NbZNhJV4EH7gt1UBW1iJMlflfitEjLgg84Osni7NVHpgce9dyf64nOtBwL6dYN239WGDvNDPpGJBKYpO/FGqQLgZvIAR0qYO7EydjUGqEJzlsnSasqdNQj/q/weqXa8k0oXft5BmUNFLo7SfQIPxy38pb6K0f/oO02rBYRs34MwHACKeYUBx5RuThlobudB+pZ13ZH6cvZj2qSaM1KoCPh8oeQ9KO80pSBBlZKd7QAwV7DQ/LvAdvwRtFPC7L5CVqgEJB8IJm3L5uOBkAVEyHmcrDw==)

spring:
  profiles:
    active: production
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${keycloak.domain}/realms/${keycloak.realm}
jwt:
  auth:
    converter:
      resource-id: authenticationClientId

keycloak:
  realm: spring-boot-code
  domain: localhost:9081
  adminClientId: admin-cli
  adminClientSecret: K84hjj8Ssum5AYKhqCMRk2tjllUouAxe
  client: authenticationClientId
  urls:
    auth: http://${keycloak.domain}
